-- MASTER SQL TO ENSURE ALL TABLES HAVE IDENTITY PROPERTIES ON THE ID COLUMN
-- This prevents "null value in column 'id'" errors during inserts.
-- This script is non-destructive (only adds missing identity property).

DO $$ 
DECLARE
    target_tables TEXT[] := ARRAY[
        'users', 'user_profiles', 'wallets', 'transactions', 'jobs', 
        'checkpoints', 'contracts', 'proposals', 'categories', 'skills', 
        'user_skills', 'job_skills', 'conversations', 'conversation_participants', 
        'messages', 'notifications', 'reviews', 'review_skill_ratings', 
        'posts', 'post_likes', 'post_comments', 'user_followers', 
        'otps', 'withdrawal_requests', 'work_sessions'
    ];
    t TEXT;
BEGIN
    FOREACH t IN ARRAY target_tables
    LOOP
        -- Check if table and id column exist
        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = t AND column_name = 'id') THEN
            -- Check if it is already an identity column
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = t AND column_name = 'id' AND is_identity = 'YES') THEN
                BEGIN
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', t);
                    RAISE NOTICE 'Added identity to table: %', t;
                EXCEPTION WHEN OTHERS THEN
                    RAISE NOTICE 'Could not add identity to table: % (Error: %)', t, SQLERRM;
                END;
            END IF;
        END IF;
    END LOOP;
END $$;
