-- COMPREHENSIVE DATABASE SCHEMA FIX
-- This script ensures all tables have Primary Keys and Unique constraints
-- Run this in Supabase SQL Editor

-- 1. Essential user-related tables
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name='users' AND constraint_type='PRIMARY KEY') THEN
        ALTER TABLE users ADD PRIMARY KEY (id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name='user_profiles' AND constraint_type='PRIMARY KEY') THEN
        ALTER TABLE user_profiles ADD PRIMARY KEY (user_id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name='wallets' AND constraint_type='PRIMARY KEY') THEN
        ALTER TABLE wallets ADD PRIMARY KEY (user_id);
    END IF;
END $$;

-- 2. Chat tables (Critical for fix)
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name='conversations' AND constraint_type='PRIMARY KEY') THEN
        ALTER TABLE conversations ADD PRIMARY KEY (id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name='messages' AND constraint_type='PRIMARY KEY') THEN
        ALTER TABLE messages ADD PRIMARY KEY (id);
    END IF;
END $$;

-- 3. Core job tables
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name='jobs' AND constraint_type='PRIMARY KEY') THEN
        ALTER TABLE jobs ADD PRIMARY KEY (id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name='contracts' AND constraint_type='PRIMARY KEY') THEN
        ALTER TABLE contracts ADD PRIMARY KEY (id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name='checkpoints' AND constraint_type='PRIMARY KEY') THEN
        ALTER TABLE checkpoints ADD PRIMARY KEY (id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name='proposals' AND constraint_type='PRIMARY KEY') THEN
        ALTER TABLE proposals ADD PRIMARY KEY (id);
    END IF;
END $$;

-- 4. Audit & Transactions
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name='transactions' AND constraint_type='PRIMARY KEY') THEN
        ALTER TABLE transactions ADD PRIMARY KEY (id);
    END IF;
END $$;

-- 5. Restore auto-increment if missing (SERIAL/IDENTITY)
-- (Only run if you see "null value in column id")
-- ALTER TABLE conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- ALTER TABLE messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- ALTER TABLE jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- ALTER TABLE transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
