-- Fix posts table schema: Add missing defaults for UUIDs and timestamps
-- Author: Antigravity
-- Date: 2026-03-15

-- 1. Fix posts table
ALTER TABLE posts ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE posts ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE posts ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

-- 2. Fix post_comments table
ALTER TABLE post_comments ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE post_comments ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

-- 3. Fix post_likes table
ALTER TABLE post_likes ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
-- Note: post_likes.id is already an identity column (GENERATED BY DEFAULT AS IDENTITY)
