-- RESTORE IDENTITY PROPERTIES TO CHAT TABLES
DO $$ BEGIN
    -- 1. Conversations table
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='conversations' AND column_name='id') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='conversations' AND column_name='id' AND is_identity='YES') THEN
            ALTER TABLE conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        END IF;
    END IF;

    -- 2. Messages table
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='messages' AND column_name='id') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='messages' AND column_name='id' AND is_identity='YES') THEN
            ALTER TABLE messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        END IF;
    END IF;
END $$;
