-- RESTORE IDENTITY PROPERTY TO OTPS TABLE
DO $$ BEGIN
    -- Check if 'id' column exists
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='otps' AND column_name='id') THEN
        -- Check if it already has an identity property
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='otps' AND column_name='id' AND is_identity='YES') THEN
            -- Add identity property
            ALTER TABLE otps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            -- Optionally restart sequence if needed, but identity handles it
        END IF;
    END IF;
END $$;
