-- FIX SOCIAL TABLES
DO $$ BEGIN
    -- 1. Fix post_likes: ensure it has a proper ID OR uses composite PK correctly
    -- If there's an 'id' column without a default, let's make it auto-increment
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='post_likes' AND column_name='id') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='post_likes' AND column_name='id' AND is_identity='YES') THEN
            ALTER TABLE post_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        END IF;
    END IF;

    -- Ensure post_likes has the correct types for foreign keys if they were somehow wrong
    -- (We checked and they were UUID for post_id, which is correct)

    -- 2. Ensure created_at and is_used defaults across tables where missing
    -- This is a general safety check
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='post_comments' AND column_name='created_at') THEN
        ALTER TABLE post_comments ALTER COLUMN created_at SET DEFAULT NOW();
    END IF;

END $$;
