-- FIX: Ensure public.users has identity and synced sequence
DO $$ 
DECLARE 
    max_id BIGINT;
BEGIN
    -- 1. Ensure Identity property exists
    -- This adds the identity property if it was lost during the data clear or previous repairs
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'id' AND is_identity = 'YES') THEN
        BEGIN
            ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            RAISE NOTICE 'Added identity to public.users';
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Could not add identity to public.users (might already exist or be serial)';
        END;
    END IF;

    -- 2. Synchronize the sequence
    -- This prevents "duplicate key value violates unique constraint" if IDs were manually inserted
    SELECT COALESCE(max(id), 0) FROM public.users INTO max_id;
    EXECUTE format('ALTER TABLE public.users ALTER COLUMN id RESTART WITH %s', max_id + 1);
    RAISE NOTICE 'Reset users identity sequence to %', max_id + 1;
END $$;
